### ISSUE TITLE
Where do you get the updated schemas?

### ISSUE THREAD

**Issue by JuanPotato** [badoualy/kotlogram#12]
May I ask where you find the updated schemas like https://github.com/badoualy/kotlogram/blob/master/tl-builder/src/main/resources/tl-schema-45.json ?

**Comment by badoualy** [comment]
M
https://github.com/zhukov/webogram/blob/master/app/js/lib/config.js#L102

**Comment by JuanPotato** [comment]
Thank you

**Comment by Darych** [comment]
Hi @badoualy !

Thank you for your library. I'm trying to reach out how to use it and how Telegram API works.
I hope I found a new version of scheme. Layer. 71:
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl
