### ISSUE TITLE
400: INPUT_CONSTRUCTOR_INVALID

### ISSUE THREAD

**Issue by zappaton** [badoualy/kotlogram#13]
Hello. Thank you for your awesome work.
I have uploaded a photo and I am trying to send it to a contact with messagesSendMedia but I get the above error.
I am doing this:
```java
TLAbsInputFile inputFile = (!isBig) ? new TLInputFile(file_id, file_parts, file.getName(), file_hash) : new TLInputFileBig(file_id, file_parts, file.getName());

TLAbsInputMedia media = new TLInputMediaUploadedPhoto(inputFile, file.getName());

TLAbsUpdates updates = TelegramManager.client.messagesSendMedia(false, new TLInputPeerUser(id, hash), null, media, TelegramManager.getRandomId(), new MarkUp());
```

Am I doing something wrong?
Best Regards.

**Comment by badoualy** [comment]
Hi, 
Can you tell me which version of the library are you using please?

**Comment by zappaton** [comment]
Ok. Yes, It is working now. I was getting a nullpointer exception when I was using null but now It is working fine and I can not replicate the error. Thanks for the answer and sorry for bothering you.

By the way, in the ex3ndr api there were two classes to handle the download and upload of files and they work in your project and I think they are very useful.
[https://github.com/ex3ndr/telegram-api/blob/master/src/main/java/org/telegram/api/engine/file/Downloader.java](url)

**Comment by badoualy** [comment]
Thanks for the share, I won't use this class for various reasons, I plan to add utils methods later to make it easier to download :)
