### ISSUE TITLE
TLUser with auth_key

### ISSUE THREAD

**Issue by MaMadLord** [badoualy/kotlogram#15]
i have a problem in creating User with auth_key, i figured to connect the app and get the notifications but i can't create a TLUser to get user name or picture etc. is it possible trough authImport method?! if it is what should i put in the argument?! i mean what are int ID and TLByte[] bytes?! i tried AppId as id and Auth as bytes but it said AUTH_BYTES_INVALID.

**Comment by badoualy** [comment]
Please check the example on the home page to check how to sign in with an existing account.
```
TelegramApp app = new TelegramApp(C.API_ID, C.API_HASH, C.MODEL, C.SYSTEM_VERSION, C.APP_VERSION, C.LANG_CODE);
TelegramClient client = Kotlogram.getDefaultClient(app, new ApiStorage());

// Send code to account
TLAbsSentCode sentCode = client.authSendCode(C.PHONE_NUMBER, 5);
System.out.println("Authentication code: ");
String code = new Scanner(System.in).nextLine(); // Input the code

  // Auth with the received code
TLAuthorization authorization = client.authSignIn(C.PHONE_NUMBER, sentCode.getPhoneCodeHash(), code);
TLUser self = authorization.getUser().getAsUser();
System.out.println("You are now signed in as " + self.getFirstName() + " " + self.getLastName());
```

**Comment by MaMadLord** [comment]
this code uses sms verification. what i said is ,i have the authorized client but i can't create  TLUser self with it. assume code below:
 `TelegramApp app = new TelegramApp(C.API_ID, C.API_HASH, C.MODEL, C.SYSTEM_VERSION, C.APP_VERSION, C.LANG_CODE);
TelegramClient client = Kotlogram.getDefaultClient(app, new ApiStorage());
`
how to use client to get TLUser self?!
i don't want to use authSignIn (im already signed in!).cause i don't want to use sms code.

**Comment by badoualy** [comment]
Well this question is related to the Telegram api, and their lack of documentation, and as I've said already a few times (in the documentation, and in opened issues) I will not do their work about api related question.

Now regarding the issue, you probably need to call `getDialogs` then find the self user in the list of users contained in the response.
