### ISSUE TITLE
get every users in group

### ISSUE THREAD

**Issue by MaMadLord** [badoualy/kotlogram#16]
i could not find any method to list every users in a chat. i recognized that the MegaGroups are treated like channels in this lib. but there is nothing to get Users in TLChannel Class.

**Comment by badoualy** [comment]
I reckon you find the solution?
By the way 

> i recognized that the MegaGroups are treated like channels in this lib.

Sadly, not my choice, MegaGroups are treated like channels in telegram's api, I have some suppositions why they choose that model but anyway, not my choice :)

**Comment by MaMadLord** [comment]
Yup i found the answer. but i can't find any method that could create TLAbsInputChannel to put it in the code below.

> client.channelsGetFullChannel( TLAbsInputChannel ).getUsers();

**Comment by badoualy** [comment]
You can create an instance of `TLInputChannel` :)

**Comment by MaMadLord** [comment]
Tnx. i just want to say one thing is confusing in your lib. you named 2 class after same name. one got flags and other got real methods. i know thats for abstraction or sth telegram suggested etc. but in java its impossible to have same name classes imported in a file. btw it's better to change their name with a sign. i.e. those in messages have m at the end of the name. etc.
