### ISSUE TITLE
how use it

### ISSUE THREAD

**Issue by amin1softco** [badoualy/kotlogram#2]
hi 
i glad to meet this project. 
i before use ex3ndr work and this project https://github.com/yarneo/telegram-trivia-bot
now i want use your project but your sample don't work for me i build 0.0.4 with gradle  and success build this library jar file tl - mtproto - api but when use your sample code new apistorage have a problem plz provide clean sample code 
sorry for bad english
best regard.

**Comment by badoualy** [comment]
Updated README with a working sample, to sendCode to phoneNumber, send signIn, and get recent conversations.

You'll need to create your 'C' class to supply all the necessary fields (such as phone number, api id, api hash, ...)

Please use
`compile 'com.github.badoualy.kotlogram:api:cbeb0b8caf'` for now, I'll release 0.0.5 soon.
