### ISSUE TITLE
kotlogram and Android

### ISSUE THREAD

**Issue by xanscale** [badoualy/kotlogram#22]
hi, i'm trying to use kotlogram for android application.

after some fails using java8 and jack it compiles but i receive connection error.

it's my fault or kotlogram cant run in android?

```
jackOptions {
	enabled true
}
compileOptions {
	sourceCompatibility JavaVersion.VERSION_1_8
	targetCompatibility JavaVersion.VERSION_1_8
}
```

```
I/art: Late-enabling -Xcheck:jni
W/System: ClassLoader referenced unknown path: /data/app/com.zerounotribe.numina.dashboard.alice-1/lib/arm64
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/System.err: [main] INFO com.github.badoualy.telegram.api.Kotlogram - 
W/System.err:          __  ___   ______   .___________. __        ______     _______ .______          ___      .___  ___.
W/System.err:         |  |/  /  /  __  \  |           ||  |      /  __  \   /  _____||   _  \        /   \     |   \/   |
W/System.err:         |  '  /  |  |  |  | `---|  |----`|  |     |  |  |  | |  |  __  |  |_)  |      /  ^  \    |  \  /  |
W/System.err:         |    <   |  |  |  |     |  |     |  |     |  |  |  | |  | |_ | |      /      /  /_\  \   |  |\/|  |
W/System.err:         |  .  \  |  `--'  |     |  |     |  `----.|  `--'  | |  |__| | |  |\  \----./  _____  \  |  |  |  |
W/System.err:         |__|\__\  \______/      |__|     |_______| \______/   \______| | _| `._____/__/     \__\ |__|  |__|
W/System.err:         Using layer 66
W/System.err:         
W/System.err: [main] WARN com.github.badoualy.telegram.api.TelegramClient - No data center found in storage, using preferred 149.154.167.91:443
W/System.err: [main] ERROR com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection - Failed to connect
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/System.err: [main] ERROR com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection - Failed to connect
W/System.err: [main] ERROR com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection - Failed to connect
D/AndroidRuntime: Shutting down VM
                  
                  
                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zerounotribe.numina.dashboard.alice, PID: 13780
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zerounotribe.numina.dashboard.alice/com.zerounotribe.numina.dashboard.activity.SplashActivity}: kotlin.KotlinNullPointerException
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: kotlin.KotlinNullPointerException
                      at com.github.badoualy.telegram.mtproto.auth.AuthKeyCreation.createAuthKeyInternal(AuthKeyCreation.kt:85)
                      at com.github.badoualy.telegram.mtproto.auth.AuthKeyCreation.createAuthKey(AuthKeyCreation.kt:50)
                      at com.github.badoualy.telegram.api.DefaultTelegramClient.generateAuthKey(DefaultTelegramClient.kt:110)
                      at com.github.badoualy.telegram.api.DefaultTelegramClient.init(DefaultTelegramClient.kt:77)
                      at com.github.badoualy.telegram.api.DefaultTelegramClient.<init>(DefaultTelegramClient.kt:70)
                      at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt:30)
                      at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient$default(Kotlogram.kt:29)
                      at com.github.badoualy.telegram.api.Kotlogram.getDefaultClient(Kotlogram.kt)
                      at com.zerounotribe.numina.dashboard.activity.SplashActivity.onCreate(SplashActivity.java:64)
                      at android.app.Activity.performCreate(Activity.java:6682)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6121) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

```

**Comment by badoualy** [comment]
Looks like there's a crash when the connection fails when creating an authorization key, I'll have a look when I have some time, in the mean time try to put the `getDefaultClient` call in a try/catch block and it shouldn't crash.

As why the connection fails, I guess there is something wrong with the device connectivity (or missing internet permission in the android manifest?)

**Comment by xanscale** [comment]
the app make REST connections correctly with my server.

i just follow "Get started" tutorial using my API_ID and API_HASH and enabled java8. it's correct?

**Comment by badoualy** [comment]
Yes, and even with invalid API_ID and API_HASH, you wouldn't have this kind of error. The issue here according to the logs is that Telegram's servers are not reachable

**Comment by xanscale** [comment]
Someone has ever tried Kotlogram on android ?
which java class is used to open socket with server?

**Comment by badoualy** [comment]
Not sure, Kotlogram was not developed for Android, and is probably not a good fit, due to battery usage, etc.
The connection is made with the `SocketChannel` class from the java nio

**Comment by xanscale** [comment]
Official Telegram App for Android make connections using NDK (so are in C/C++) and is not simple to understands code.

i think this library can be usefull if supports Android officially.

i don't know if there is many works or not. there is many low level code

https://developer.android.com/reference/java/nio/channels/SocketChannel.html
https://docs.oracle.com/javase/7/docs/api/java/nio/channels/SocketChannel.html

**Comment by J-rooft** [comment]
I'm using Kotlogram for my android app with some modifications: I updated the code to use Java 7 and before, because jack compiler is not supported anymore and java 8 native support is not yet released.
I agree that Kotlogram is not the best Telegram library for android, e.g. it makes network connection in constructor, so you must not call `Kotlogram.getDefaultClient(...)` on main thread.

**Comment by badoualy** [comment]
It would require a lot of work, especially due to mobile restrictions, battery consumption issues, ...
Currently the developer would have to code everything, usage of gcm/fcm, close connection after idle time to save battery...
Sadly I don't have the time to do this kind of work right now.
I should be able to easily update the lib to use java 7 since most of the lib is written in Kotlin anyway, this would be a nice start.

**Comment by xanscale** [comment]
thz for all this comments :)

I think a good start is that it works, then refinements can be made to improve the various aspects

java 7 is a good start, after we need to know why i cant connect.

@J-rooft Have you ever received an error like mine?

**Comment by J-rooft** [comment]
@xanscale yes, I had the same error. I cloned the repo and updated `com.github.badoualy.telegram.mtproto.auth.AuthKeyCreation` class. I removed line 73:
```
logger.debug(connection!!.marker, "Key created after ${i + 1} attempt in ${System.currentTimeMillis() - start} ms")
connection = null // I removed this
return authResult
```

**Comment by xanscale** [comment]
seams a bug and not an android porting problem. not?

**Comment by J-rooft** [comment]
yes, it looks so, because `connection` is set to `null` even though it is used later

**Comment by badoualy** [comment]
`connection` is set to null in the `AuthKeyCreation` singleton, but it's not disconnected, and still existing in the `authResult`
The issue here is elsewhere, see the logs:
```
W/System.err: [main] ERROR com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection - Failed to connect
W/System.err: [main] ERROR com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection - Failed to connect
```

**Comment by J-rooft** [comment]
in AuthKeyCreation on line 70 if `MTProtoTcpConnection(dataCenter.ip, dataCenter.port, tag)` will throw exception then `connection` will `null` and in try catch block `connection!!.close()` will be called on null object and will throw `KotlinNullPointerException `

**Comment by J-rooft** [comment]
@xanscale make sure that you have `android.permission.INTERNET` and `android.permission.WRITE_EXTERNAL_STORAGE` permissions.

You can check how I initialize Kotlogram [here](https://github.com/J-rooft/Telesam/tree/develop/app/src/main/java/space/naboo/telesam/telegram)

**Comment by xanscale** [comment]
my app actually use this permissions:
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by xanscale** [comment]
@J-rooft what is this?

`val prodDc = DataCenter("149.154.167.50", 443)`

i must configure server ip?

**Comment by badoualy** [comment]
Nope, no need to do it manually, unless you want to connect to a specific datacenter at first connection, Kotlogram handles that, and even if you do, all the datacenters are listed in Kotlogram singleton, no need to re-hardcode them.

**Comment by xanscale** [comment]
@badoualy there is any schedule to switch to java 7? i use annotation processor in my app and seams that can create problem with java 8. i don't know if this is the problem

**Comment by badoualy** [comment]
Try RC2, now using java 7 :)

**Comment by xanscale** [comment]
hudston we have a problem :)

in row 56 of AuthKey class you use longValueExact that is only java 8

i see you have set compatibility to 1.7, why you not received error?

**Comment by xanscale** [comment]
i just discovered this:

https://stackoverflow.com/questions/42550985/android-studio-can-not-find-java-math-biginteger-some-methods-in-project

even if put target to java 8, android is not full java 8 compliant

**Comment by badoualy** [comment]
Ok, I'll fix ASAP

**Comment by badoualy** [comment]
Any other errors while I'm at it?

**Comment by xanscale** [comment]
app crashing on this line, i don't know if there is any other.

if you make a commit i try it directly using jitpack in this moment

**Comment by xanscale** [comment]
longValueExact are used 4 times in your project

**Comment by badoualy** [comment]
`73f8c8c`

**Comment by xanscale** [comment]
now compile and works up to authSendCode. i will try other methods

**Comment by badoualy** [comment]
I just pushed another commit fixing the original crash (just realized it was still not fixed)

**Comment by xanscale** [comment]
ok. i always use your last commit to integrate library in my app and send open bug.

thz for all your support and your library. 

bye

**Comment by J-rooft** [comment]
Regarding java 7 support I also found this:
`Byte.toUnsignedInt()` is used in `ByteBufferUtils.readBytaAsInt(ByteBuffer)`

**Comment by J-rooft** [comment]
I made a pull request in this one: https://github.com/badoualy/kotlogram/pull/27

**Comment by badoualy** [comment]
Fixed :)
