### ISSUE TITLE
AuthKey must be 256 Bytes found 360 bytes

### ISSUE THREAD

**Issue by luzzif** [badoualy/kotlogram#23]
I'm using the exact same API storage as the example given in this repo, but when the library tries to read the authorization key from the file, it finds nothing, since the library just started and I don't really know what to put in the file to begin with. What should the file contain right off the bat?

**Comment by J-rooft** [comment]
If library does not find then auth key will be generated automatically. You can check it in `DefaultTelegramClient` class in `private fun init(checkNearestDc: Boolean = true)` method

**Comment by luzzif** [comment]
I keep on having the same error. Do I have to change something in order for it to work?

**Comment by luzzif** [comment]
Seems like I got it to work, but when I try to make a request (lets say, to get the app update) it throws an RpcErrorException, saying 401:AUTH_KEY_UNREGISTERED

**Comment by J-rooft** [comment]
You first need to authorize the user as described [here](https://core.telegram.org/api/auth)

So you first need to call `telegramClient.authSendCode()`
and then `telegramClient.authSignIn()` with phone hash from first call and code entered by a user

**Comment by luzzif** [comment]
Thank you, it now works!
