### ISSUE TITLE
how to check if client are already logged in or login are required?

### ISSUE THREAD

**Issue by xanscale** [badoualy/kotlogram#28]
as title

**Comment by J-rooft** [comment]
I use `client.usersGetFullUser(TLInputUserSelf())` method, if user is logged in then it will return `TLUserFull`, otherwise it will throw `RpcErrorException` with `RpcErrorException.code == 401`

**Comment by xanscale** [comment]
how to get TLAbsInputUser ?

**Comment by J-rooft** [comment]
`TLAbsInputUser` is a super class of `TLInputUserSelf`. So you can pass `TLInputUser`, `TLInputUserEmpty` or `TLInputUserSelf` to `client.usersGetFullUser()`. If you want to use `TLInputUser`, then you need to receive user id and access hash for this user, using for example `client.messagesGetDialogs()` method

**Comment by badoualy** [comment]
Pretty much doing the same here.
You can also store the user info after you call `auth.signIn` method, this way, if you have the info, it means you are logged in, but beware that the user can revoke the auth key at anytime via the official app settings, so you should handle the RpcError anyway :)

**Comment by xanscale** [comment]
thz for all support @badoualy @J-rooft 

I have some other support request, can i open bug for that or there is a better channel?

**Comment by badoualy** [comment]
Open an issue for bugs/questions related to the library, but I might not have the time to answer questions related to the Telegram API (as explained in the README, it's their jobs to do that, but apparently they don't want to) :)
