### ISSUE TITLE
How to Join a Channel

### ISSUE THREAD

**Issue by hosseinab** [badoualy/kotlogram#3]
Hi 
Thanks for your straightforward project…
I want to join to channels (either public and private but the public is my issue mostly) via "UserName" but for this goal I can't obtain "channel id" and "Access_Hash" to make new objects from "InputChannel" and pass it to "TLRequestChannelsJoinChannel"
Thanks

**Comment by badoualy** [comment]
As specified in the README, this question is related to the lack of documentation of Telegram current API level.

Sadly, I don't have the time (nor the will) to do their job, if I had an easy response I would answer you, but I never used this feature, and don't have time to investigate.

**Comment by amalagaura** [comment]
@hosseinab You want to use client.contactsResolveUsername. Then try to cast the result.peer to TLPeerChannel to resolve the id from a name. AccessHash is for groups, I don't think you need it.
