### ISSUE TITLE
how to have UpdateCallback without specify preferredDataCenter ?

### ISSUE THREAD

**Issue by xanscale** [badoualy/kotlogram#31]
to get update callback we need to initialize TelegramClient with this method

```
   @JvmStatic
   @JvmOverloads
   @NotNull
   public static final TelegramClient getDefaultClient(@NotNull TelegramApp application, @NotNull TelegramApiStorage apiStorage, @NotNull DataCenter preferredDataCenter, @Nullable UpdateCallback updateCallback) {
      return getDefaultClient$default(application, apiStorage, preferredDataCenter, updateCallback, (String)null, 16, (Object)null);
   }
```

in this way `@NotNull DataCenter preferredDataCenter` so i cant use default DataCenter and receive update callback

it's a bug or I do not understand somethings ?

**Comment by badoualy** [comment]
Just pass `Kotlogram.PROD_DC4`. I use this one because this is the DC for France (and Europe I think) :)

**Comment by badoualy** [comment]
In RC4 release, updateCallback will switch position with datacenter
