### ISSUE TITLE
Add "OnError" handling

### ISSUE THREAD

**Issue by vishnyakov-aleks** [badoualy/kotlogram#36]
Please resolve this, old, like the world, problem.

In some situations new session after "reached end of stream" not started. It happens, when OnError not catches.

See attachment with stacktrace, please
![kazam_screenshot_00014](https://user-images.githubusercontent.com/17671328/29917522-e708b8d6-8e4a-11e7-8f22-ad745e022116.png)

**Comment by badoualy** [comment]
Should be fixed with https://github.com/badoualy/kotlogram/commit/65c96ce2862b29425dcfcf26da39f776f57d1253

**Comment by vishnyakov-aleks** [comment]
Please tell, when will be the release fix this commit?

**Comment by badoualy** [comment]
No plan yet,
use
```gradle
compile 'com.github.badoualy.kotlogram:api:65c96ce'
```
in the mean time

**Comment by vishnyakov-aleks** [comment]
Thanks, I will try today

**Comment by vishnyakov-aleks** [comment]
handle works, but my connections not up.... 2 of 3 broken in 2 minutes after start =(
![kazam_screenshot_00016](https://user-images.githubusercontent.com/17671328/29946652-dec93cb8-8eae-11e7-9c5a-b953b647a068.png)

**Comment by badoualy** [comment]
see #33 for this issue

**Comment by vishnyakov-aleks** [comment]
I already seen it and post my screenshots there
Connections are drops every time on some of pool clients. 
I need to reboot my server side every 5 minutes :(

**Comment by badoualy** [comment]
Yeah, I have no clue why it's doing this sadly ...
Seems worse after removing the KEEP_ALIVE. I'll revert this change.

**Comment by vishnyakov-aleks** [comment]
Please? when do you can to do it?

**Comment by badoualy** [comment]
5f8590d5e1

**Comment by vishnyakov-aleks** [comment]
https://github.com/badoualy/kotlogram/commit/5f8590d5e198362a54b4ad867e877793006b3a11


did not help

**Comment by badoualy** [comment]
I just reverted the changes on KEEP_ALIVE which seems to have make things worse.
Please take further discussion about end-of-stream issues in #33 
As I said there, I'm clueless as why this happens, and am pretty much stuck.
