### ISSUE TITLE
How to disable debug out?

### ISSUE THREAD

**Issue by vishnyakov-aleks** [badoualy/kotlogram#37]
i dont need messages, like readMessage? can i disable it?
![kazam_screenshot_00015](https://user-images.githubusercontent.com/17671328/29946458-197b8e16-8eae-11e7-8245-8e060f13cf6d.png)

**Comment by RanolP** [comment]
I solved this problem by changing log level
Here is my code:
```java
System.setProperty(SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
```

Sorry for my bad English ;(

**Comment by badoualy** [comment]
Solution above should work, a cleaner solution would be a resource file, see [https://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple](How to configure slf4j-simple) for more details.
