### ISSUE TITLE
 send a message to a phone number

### ISSUE THREAD

**Issue by l3g3nd95** [badoualy/kotlogram#38]
How do I send a message to a phone number? Thanks.
 I found how to send to a username but to a phone number nothing.
`final TLResolvedPeer tstuser = client.contactsResolveUsername("xxxxxxx");`
 `final TLAbsUser peer = tstuser.getUsers().get(0);`
 `TLInputPeerUser inputUser = new TLInputPeerUser(peer.getId(), ((TLUser) peer).getAccessHash());`
 `int randomId = new Random(System.currentTimeMillis()).nextInt();`
 `client.messagesSendMessage(inputUser, "Kotlogram!", randomId);`

**Comment by badoualy** [comment]
I don't think it's possible, you probably need to retrieve a user from the phone number via another call first.

**Comment by l3g3nd95** [comment]
I've seen something in the  source code of android app... would you refer to something like that?
from line 145
[https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/ui/NewContactActivity.java](url)

**Comment by badoualy** [comment]
Yes, it's using the `contactsImportContacts` method.
