### ISSUE TITLE
Using TCP tunneling for faster messages updates

### ISSUE THREAD

**Issue by JackPoteYes** [badoualy/kotlogram#40]
Hi,
The API has the the TCP feature on top of the http one.
It means that we can connect via one TCP session, instead of sending http requests to the server in order to get new messages.
Via TCP, messages are delivered asap without having to poll.

Is there a way to use this feature with Kotlogram ? I need to receive a message asap within a known time interval, where every milisecon counts.

**Comment by badoualy** [comment]
Kotlogram is currently relying on a TCP socket only, the HTTP transport is not implemented.

**Comment by JackPoteYes** [comment]
What a good news. Thank you.
