### ISSUE TITLE
users.getUsers

### ISSUE THREAD

**Issue by lulululbj** [badoualy/kotlogram#44]
Thanks.

When a user which isn't  my friend  send a message to me for a first time, how can I get his basic userinfo?
In the `TLRPC.Updates` returned with the new message, I can only get the field `user_id`, but the api 
 [users.getUsers](https://core.telegram.org/method/users.getUsers) requires two parametres : `user_id` and `access_hash`

**Comment by badoualy** [comment]
Just try with 0

**Comment by stek29** [comment]
0) Cache access_hash'es for user_id's locally
1) If you're not dropping updates, telegram should send a Updates with new users
2) If you don't have hash cached and didn't get an update (yet?), use messages.getMessages
  It returns `messages.Messages`, which has `users` and `chats` vectors.

partially copy-pasted from Traitor's messages.

**Comment by lulululbj** [comment]
Thanks， I will  have a try .
