### ISSUE TITLE
How to determine if client is authorized ?

### ISSUE THREAD

**Issue by applke** [badoualy/kotlogram#45]
How to determine if client is authorized or need to request a code?

**Comment by badoualy** [comment]
Use method `getUser` with self, it'll fail if you're not signed in

**Comment by applke** [comment]
by  client.executeRpcQuery() ?

**Comment by J-rooft** [comment]
@applke It was discussed in https://github.com/badoualy/kotlogram/issues/28

**Comment by applke** [comment]
or client.getUser() ? If this, than i have an issue. I don't have this method...
