### ISSUE TITLE
Callback not firing for new messages

### ISSUE THREAD

**Issue by amalagaura** [badoualy/kotlogram#5]
I have a valid connection up but not getting new messages via the callback class.

I ran a debugger and see that `selector.select(SELECT_TIMEOUT_DELAY)` is returning 0 as the nio.channel selector is not able to select a channel. But that is happening on a thread wakeup on a regular interval so maybe that is not related to incoming messages?

The debugger shows that `register` in MTProtoTcpConnection correctly registers a channel to the selector and returning a selectionKey to put in the keyMap.

I don't know how to debug further because I am not sure where the triggers should happen.

I  just have a single client that I instantiate with Kotlogram.getDefaultClient and I pass a callback to it.  I think there have been weird issues with datacenters, maybe that is an issue? I just picked a datacenter when authorizing the token and now it has a datacenter stored via the ApiStorage interface.

**Comment by badoualy** [comment]
`selector.select` will return 0 after a given delay of inactivity, then re-call select.

If you give a callback to the getDefaultClient, it will be called, I've been using it and never had any issue, and I don't see why you wouldn't.

Did you enable logs? `Kotlogram.setDebugLog` before creating the client.

Sometimes a connection to Telegram datacenter will fail, and you'll see a `reached-end-of-stream` exception, not sure on which side is the issue. I plan to re-write the network part using netty when I'll have some time.

Please enable the log and check if any exception or error message are present

**Comment by amalagaura** [comment]
OK I made progress. I was using the latest commit. I was doing it manually because I did not know you could use the git hash in gradle, but I will do that now instead.

Thank you for the response. I do have the logs enabled and got these messages when the client started:

```
[main] MTProtoTcpConnection# Connected to 149.154.175.50:443
[main] MTProtoHandler#-7662255704637640542# New session id created
[main] TelegramClient# Client ready with MTProto#-7662255704637640542
```

I was not getting any exceptions but was not getting messages either

Then I had the client perform an RPC action. And **after that** I start getting the subscription callbacks. So there is some subtle issue where the channel gets activated after a write. It then works perfectly and I am getting all actions.

I did see this something about a bad server salt, so maybe it needs to do some negotiation on a write and then it is able to receive messages. I am pasting a log:

```
[main] MTProtoTcpConnection# Connected to 149.154.175.50:443
[main] MTProtoHandler#-4753342306315848209# New session id created
[main] TelegramClient# Client ready with MTProto#-4753342306315848209
[qtp533707983-26] MTProtoHandler#-4753342306315848209# executeMethod contacts.resolveUsername#f93ccba3
[qtp533707983-26] MTProtoHandler#-4753342306315848209# Sending method with msgId 6257526282347610112 and seqNo 1
[qtp533707983-26] MTProtoHandler#-4753342306315848209# Sending message with msgId 6257526282347610112 and seqNo 1
[pool-4-thread-1] MTProtoTcpConnection# About to read a message of length 88
[pool-4-thread-1] MTProtoWatchdog# New message of length: 88
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# Received msg 6257526284240575489 with seqNo 0
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# handle bad_server_salt#edab447b
**[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# {id: 6257526282347610112, seqNo: 1, errorCode: 48, errorMessage: incorrect server salt}**
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# Re-sending message 6257526282347610112 with new salt
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# Sending message with msgId 6257526282347610112 and seqNo 1
[pool-4-thread-1] MTProtoTcpConnection# About to read a message of length 152
[pool-4-thread-1] MTProtoWatchdog# New message of length: 152
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# Received msg 6257526284405264385 with seqNo 2
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# Message is a container
[RxComputationThreadPool-3] MTProtoHandler#-4753342306315848209# Container has 2 items
```

Hope this makes sense.

**Comment by badoualy** [comment]
Yes, sadly, You need to make a first RPC call when you create your client, basically so that Telegram will know "who you are" (from your auth_key).

For git hash in gradle => It's because I'm using jitpack, awesome tools that creates a maven repo with all git repo, to avoid having to deal with annoying mavenCentral configuration... :)

So issue closed?

**Comment by amalagaura** [comment]
Yes thank you for the clarification. It works great after I make a simple RPC call. Thank you for the library. I have gone through a lot of the code and it is well organized and written really well.

**Comment by badoualy** [comment]
Next version will execute 1 rpc request when creating a client automatically, so you won't have this issue anymore.
