### ISSUE TITLE
how to call getMessagesViews

### ISSUE THREAD

**Issue by hosseinab** [badoualy/kotlogram#6]
hi
 I want to calling getMessagesViews method . 
 please help me about parameters of this method . 
 InputPeer peer { channelId , accessHash}
 Vector id
 boolean increment

I call ChannelsGetDialogs for parameters and get chat object of my channel and put chat id into channelid and access hash , is it ok ?

after get message object of channel and add message id into vector id .
 and equals increment with true

but when I call the method received timeout exception .

thanks a lot

**Comment by badoualy** [comment]
As I said in your previous ticket #3 , this question is related to the lack of documentation on Telegram side, and I don't have the time to investigate, I never used any API call related to channels, so I won't be able to help you on this, keeping the issue open if someone has an answer for you.

All I can say is that if you receive a timeout exception, it means you didn't receive a correct response for this request, but I can't say why without the logs.

Regards.

**Comment by badoualy** [comment]
Should be fixed with 
```gradle
compile 'com.github.badoualy:kotlogram:453951a73e'
```

Some methods were trying to deserialize int, long and string vectors as TLObject vectors
